name: build latest wg-roaming and upload docker image
  
on: [push]

env:
  GO_VERSION: "1.23"
  REPOSITORY: "yanmarques/wg-roaming"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set tag 
        run: echo "GIT_TAG=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REPOSITORY }}
          flavor: latest=false
          tags: |
            type=ref, event=branch

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build multi-arch Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: images/Dockerfile
          push: true
          platforms: linux/amd64
          tags: "ghcr.io/${{ env.REPOSITORY }}:latest"
          build-args: TAG=${{ env.GIT_TAG }}

